package chakriprog;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
public class Test8
{
	public static void main(String[] args) throws Exception
	{
		ChromeOptions options = new ChromeOptions();
		options.addArguments("--disable-notifications");
		System.setProperty("webdriver.chrome.driver", "D:\\softwaretesting\\chromedriver.exe");
		WebDriver chakri =new ChromeDriver(options);
		//Launch facebook
		chakri.get("http://www.facebook.com");
		Thread.sleep(5000);
		chakri.manage().window().maximize();
		//Login
		chakri.findElement(By.name("email")).sendKeys("chakrapanibandhu@yahoo.com");
		Thread.sleep(5000);
		chakri.findElement(By.name("pass")).sendKeys("chakri");
		chakri.findElement(By.xpath("(//*[@aria-label='Log In'])")).click();
		Thread.sleep(5000);
		chakri.findElement(By.xpath("//*[contains(@data-tooltip-content,'Messages')]")).click();
		Thread.sleep(5000);
		chakri.findElement(By.xpath("(//*[contains(@class,'messagesContent')])[2]")).click();
		Thread.sleep(5000);
		chakri.findElement(By.xpath("//div[contains(@role,'combobox')]")).sendKeys("hi this message is generated by testing automation");
		Thread.sleep(5000);
		chakri.findElement(By.xpath("//*[contains(@d,'M11,8.3L2.6,8.8C2.4,8.8,2.3,8.9,2.3,9l-1.2,4.1c-0.2,0.5,0,1.1,0.4,1.5C1.7,14.9,2,15,2.4,15c0.2,0,0.4,0,0.6-0.1l11.2-5.6 C14.8,9,15.1,8.4,15,7.8c-0.1-0.4-0.4-0.8-0.8-1L3,1.1C2.5,0.9,1.9,1,1.5,1.3C1,1.7,0.9,2.3,1.1,2.9L2.3,7c0,0.1,0.2,0.2,0.3,0.2 L11,7.7c0,0,0.3,0,0.3,0.3S11,8.3,11,8.3z')]")).click();
		Thread.sleep(5000);
		chakri.findElement(By.xpath("//*[contains(@id,'userNavigationLabel')]")).click();
		Thread.sleep(5000);
		chakri.findElement(By.name("//*[contains(@class,'_54ni navSubmenu _6398 _64kz __MenuItem')]")).click();
		Thread.sleep(5000);
		chakri.findElement(By.xpath("//li[@class='_54ni navSubmenu _6398 _64kz __MenuItem']//a[@class='_54nc']//span//span[@class='_54nh']")).click();
		//close site
		chakri.close();
		
	}

	}

